general {
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = /usr/share/backgrounds/sable/wallpaper.png
    blur_passes = 2
    blur_size = 4
    color = rgba(101010ff)
}

input-field {
    monitor =
    size = 300, 52
    outline_thickness = 1
    outer_color = rgba(f4f4f5dd)
    inner_color = rgba(141414ee)
    font_color = rgba(f4f4f5ff)
    placeholder_text = Password
    fail_text = Authentication failed
    position = 0, -80
}

label {
    monitor =
    text = Sable
    color = rgba(f4f4f5ff)
    font_size = 30
    position = 0, 40
}
