---
efiSystemPartition: /boot/efi
efiSystemPartitionSize: 1024M
defaultFileSystemType: btrfs
availableFileSystemTypes:
  - btrfs
  - ext4
userSwapChoices:
  - none
drawNestedPartitions: true
alwaysShowPartitionLabels: true
allowManualPartitioning: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultPartitionTableType: gpt
allowLuks: true
