---
unpack:
  - source: /run/sable-live-root
    sourcefs: file
    destination: ""
    exclude:
      - /boot/efi/*
      - /dev/*
      - /lost+found
      - /media/*
      - /mnt/*
      - /proc/*
      - /run/*
      - /sys/*
      - /tmp/*
