timeout: 4
default_entry: Sable Bootstrap Preview
remember_last_entry: no
interface_branding: SABLE / BOOTSTRAP PREVIEW
interface_branding_color: f4f4f5
interface_help_hidden: yes
wallpaper: boot():/EFI/sable/wallpaper.png
wallpaper_style: cover
backdrop: 050505
term_background: c0101010
term_foreground: f4f4f5
term_palette: 0b0b0b;3f3f46;52525b;71717a;a1a1aa;d4d4d8;e4e4e7;f4f4f5
term_palette_bright: 18181b;52525b;71717a;a1a1aa;cbd5e1;e4e4e7;f8fafc;ffffff
term_margin: 56
term_margin_gradient: 16

/Sable Bootstrap Preview
    comment: Graphical development environment
    protocol: linux
    path: boot():/EFI/sable/vmlinuz-linux-lts
    module_path: boot():/EFI/sable/initramfs-linux-lts.img
    cmdline: root=UUID=@ROOT_UUID@ rootfstype=btrfs rw rootflags=compress=zstd,nodiscard console=tty0 console=ttyS0,115200 lsm=landlock,lockdown,yama,integrity,apparmor,bpf systemd.unit=graphical.target

/Sable Recovery Console
    comment: Text mode with verbose boot output
    protocol: linux
    path: boot():/EFI/sable/vmlinuz-linux-lts
    module_path: boot():/EFI/sable/initramfs-linux-lts.img
    cmdline: root=UUID=@ROOT_UUID@ rootfstype=btrfs rw rootflags=compress=zstd,nodiscard console=tty0 console=ttyS0,115200 lsm=landlock,lockdown,yama,integrity,apparmor,bpf systemd.unit=multi-user.target
