[options]
Architecture = auto
CheckSpace
Color
ParallelDownloads = 10
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
HookDir = /etc/pacman.d/sable-bootstrap-hooks

[cachyos]
SigLevel = Required DatabaseOptional
Server = https://at.cachyos.org/repo/$arch/$repo

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
