[options]
Architecture = auto
CheckSpace
ParallelDownloads = 5
SigLevel = Required DatabaseOptional TrustedOnly
LocalFileSigLevel = Required

[sable-core]
Server = https://repo.example.invalid/sable/testing/sable-core/$arch

[sable-desktop]
Server = https://repo.example.invalid/sable/testing/sable-desktop/$arch

[sable-extra]
Server = https://repo.example.invalid/sable/testing/sable-extra/$arch
