font_family DejaVu Sans Mono
font_size 11.0
background #101010
foreground #f4f4f5
selection_background #f4f4f5
selection_foreground #101010
background_opacity 0.88
dynamic_background_opacity yes
confirm_os_window_close 0
window_padding_width 8
enable_audio_bell no
