[options]
Architecture = auto
CheckSpace
Color
ParallelDownloads = 5
SigLevel = Required DatabaseOptional TrustedOnly
LocalFileSigLevel = Required

[os-core]
Server = https://repo.example.invalid/os_name/stable/os-core/$arch

[os-desktop]
Server = https://repo.example.invalid/os_name/stable/os-desktop/$arch

[os-extra]
Server = https://repo.example.invalid/os_name/stable/os-extra/$arch
