---
modules-search: [ local, /usr/lib/calamares/modules ]
instances:
  - id: os_name_preflight
    module: shellprocess
    config: os_name_preflight.conf
  - id: os_name_limine
    module: shellprocess
    config: os_name_limine.conf
sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - os_name_preflight
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - hwclock
      - services-systemd
      - initcpiocfg
      - os_name_limine
      - umount
  - show:
      - finished
branding: os_name
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
