---
modules-search: [ local, /usr/lib/calamares/modules ]
instances:
  - id: sable_preflight
    module: shellprocess
    config: sable_preflight.conf
  - id: sable_limine
    module: shellprocess
    config: sable_limine.conf
  - id: sable_finalize
    module: shellprocess
    config: sable_finalize.conf
sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - shellprocess@sable_preflight
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - hwclock
      - services-systemd
      - initcpiocfg
      - initcpio
      - shellprocess@sable_finalize
      - shellprocess@sable_limine
      - umount
  - show:
      - finished
branding: sable
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
